name: CI

on:
  push:
    branches:
      - main  # Remplace par la branche de ton choix
  pull_request:
    branches:
      - main  # Exécute les tests sur les demandes de tirage vers la branche principale

jobs:
  test:
    runs-on: ubuntu-latest  # Utiliser un environnement Ubuntu

    steps:
      - name: Purge Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - name: Checkout code
        uses: actions/checkout@v2  # Vérifier le code de la branche

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Spécifie la version de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Projet-5-ML/requirements.txt  # Installe les dépendances depuis requirements.txt
     
      - name: Set FLASK_APP
        run: |
          export FLASK_APP=Projet-5-ML/flask_app.py  # Indiquer où est votre application Flask

      - name: Start Flask app
        run: |
          flask --app Projet-5-ML.flask_app run --host=127.0.0.1 --port=8000 &
          sleep 10  # Attendre que l'application démarre
          
      - name: Run tests
        run: |
          pytest Projet-5-ML/tests/  # Exécute tous les tests dans le dossier tests/
